### ISSUE TITLE
The {graphqlPath} in index.html for graphiql does not take context-path into account

### ISSUE THREAD

**Issue by lucaslilja** [micronaut-projects/micronaut-graphql#168]
### Steps to Reproduce

1. Install Micronaut and micronaut-graphql
2. Use any of the examples in this project
3. Set micronaut.server.context-path to /some/random/path in application.yml
4. Add settings to enable graphiql (defaults will do)
5. Go to the graphiql index page

### Expected Behaviour

The index.html should post to /some/random/path/graphql

### Actual Behaviour

The page will post to /graphql

### Environment Information

- **Micronaut Version:** 2.3.1
- **JDK Version:** 11.0.7
- **micronaut-graphql Version** 2.2.0

### Proposed solution

Add HttpServerConfiguration to GraphiQLController and add the contextPath to the parameters Map. Add this variable to the index.html:
`return fetch('${contextPath}${graphqlPath}', {...}`

**Comment by GoodforGod** [comment]
We have the same annoying behavior, we have different environments, with paths to services some think like 
1. www.dev.domain.com/dev_path/to/service/${graphqlPath}
2. www.test.domain.com/test_path/to/service/${graphqlPath}
Add we have to override default index.html only to ensure correct behavior, that GraphiQL doesn't post to www.dev.domain.com/${graphqlPath} but -> www.dev.domain.com/dev_path/to/service/${graphqlPath}

I would like to propose change for such behavior in index.html

**Comment by ilopmar** [comment]
Fixed by #201
