### ISSUE TITLE
Deploying Micronaut GraphQL API to AWS Lambda

### ISSUE THREAD

**Issue by limcheekin** [micronaut-projects/micronaut-graphql#24]
Is it possible to deploy Micronaut GraphQL API to AWS Lambda?

Please see the issue I faced in the following post:
https://github.com/micronaut-projects/micronaut-aws/issues/93

Thank you.

**Comment by Doogiemuc** [comment]
I found this article quite helpfull: https://guides.micronaut.io/micronaut-function-aws-lambda/guide/index.html

**Comment by limcheekin** [comment]
Thanks for sharing.

I'm aware about the article, unluckily it doesn't help the issue on hand.

**Comment by limcheekin** [comment]
Please see the workaround at https://github.com/micronaut-projects/micronaut-aws/issues/93
