### ISSUE TITLE
Add support for subscriptions

### ISSUE THREAD

**Issue by alediaferia** [micronaut-projects/micronaut-graphql#3]
Spec: https://facebook.github.io/graphql/June2018/#sec-Subscription
Example using [graphql-java](https://github.com/graphql-java/graphql-java): https://github.com/graphql-java/graphql-java-subscription-example

**Comment by kyrogue** [comment]
Looking for support/examples on subscription too

**Comment by marceloverdijk** [comment]
I'm looking into subscriptions support, including a Micronaut GraphQL example.

**Comment by gklijs** [comment]
There is also https://github.com/apollographql/subscriptions-transport-ws/blob/master/PROTOCOL.md which probably should be moved to GraphQL foundation in time, but is used by several server implementations as guideline.

**Comment by gklijs** [comment]
I'm working on a pr, I do need to be able to set the subprotocol for the websocket, so it will be based on micronaut 1.3.0 M2 https://github.com/micronaut-projects/micronaut-core/blob/v1.3.0.M2/websocket/src/main/java/io/micronaut/websocket/annotation/ClientWebSocket.java

**Comment by gklijs** [comment]
To be able to use it in chrome also, I needed a change in micronaut-core, so awaiting that, and some other things left to fix, https://github.com/micronaut-projects/micronaut-graphql/pull/27.

I validated the pr with, https://github.com/openweb-nl/kafka-graphql-examples/tree/ge-micronaut/graphql-endpoint using both queries and subscriptions over the websocket. I'll probably run some performance test soon.

**Comment by gklijs** [comment]
@alediaferia @kyrogue All that's left is a merge in micronaut-core in order for the server to work with requests made from chrome. So for now you first need to build https://github.com/gklijs/micronaut-core/tree/support-subprotocols-websocket-server. It would be great if you could take a look at the pr and provide feedback.

**Comment by gklijs** [comment]
The pr to core was fix, so you could just build https://github.com/micronaut-projects/micronaut-core now, I'm not aware. I still have to run some more tests, but so far it seems to do a bit better than graphql-spring-boot-starter. It's just a subscriptions heavy demo running on my laptop, but it might give some insights.

Some results, https://graphql.gklijs.tech/results/graphql-servers/99-latency where you can see the latency is a bit less with micronaut then any of the other implementations. And https://graphql.gklijs.tech/results/graphql-servers/average-ge-mem where micronaut needs less memory. I have to try with the more aggressive jvm settings I used for Clojure, if micronaut will also work, then reducing memory used for micronaut even further.

**Comment by marceloverdijk** [comment]
Closed via #27.
