### ISSUE TITLE
Upgrade graphql-java dependency

### ISSUE THREAD

**Issue by gklijs** [micronaut-projects/micronaut-graphql#30]
A new graphql-java version was released, which is meant to be an lts release https://github.com/graphql-java/graphql-java/releases/tag/v14.0. I could make a pr for the update. It's probably just update the dependency, but there are a few breaking changes.

**Comment by marceloverdijk** [comment]
Yes, that would be nice. Otherwise I do it myself in the weekend ;-) Don't have time today.

**Comment by marceloverdijk** [comment]
Let's target this for `1.2.2`. I will make a release this weekend.

**Comment by gklijs** [comment]
https://github.com/micronaut-projects/micronaut-graphql/pull/31 just changing the dependency was enough

**Comment by marceloverdijk** [comment]
Fixed via #31
