### ISSUE TITLE
Graphql WS with new graphql-ws protocol

### ISSUE THREAD

**Issue by phanx164** [micronaut-projects/micronaut-graphql#301]
### Feature description

The current Graphql WS [implementation](https://github.com/micronaut-projects/micronaut-graphql/blob/30ea9f7e2fb2aec157622aa575e41043a7d0e288/graphql/src/main/java/io/micronaut/configuration/graphql/ws/GraphQLWsController.java#L40) is using deprecated protocol subscriptions-transport-ws from apolo. There is a new protocol available, can we migrate to this new [protocol](https://github.com/enisdenjo/graphql-ws) 
 
https://github.com/apollographql/subscriptions-transport-ws/blob/master/README.md

**Comment by sdelamo** [comment]
@jeremyg484 @wetted can you give me status update of this issue?

**Comment by jeremyg484** [comment]
> @jeremyg484 @wetted can you give me status update of this issue?

I have reviewed the [new protocol](https://github.com/enisdenjo/graphql-ws/blob/master/PROTOCOL.md) fairly thoroughly. It is relatively simple and I don't think we should have any problem with writing an implementation for it. That said, it is different enough from the previous protocol that a from-scratch implementation would be best, and as I understand it the deprecated Apollo subscriptions-transport-ws protocol is still in use by GraphQL clients enough that we should continue to support it for now and maintain them both.

I am happy to do the work to implement the newer protocol, it's just a matter of prioritization and finding the cycles to do it. If we need it to be part of 4.0.0-M4 as indicated, then I'll dedicate the time ASAP.

**Comment by sdelamo** [comment]
@jeremyg484 lets make this happen prior to 4 GA
