### ISSUE TITLE
Add support for GraphQL v20

### ISSUE THREAD

**Issue by HelLViS69** [micronaut-projects/micronaut-graphql#334]
### Feature description

GraphQL recently released version 20, which include many new features and improvements, including support for java records

**Comment by donbeave** [comment]
The `graphql-java` 20 has already merged: https://github.com/micronaut-projects/micronaut-graphql/pull/385.

Please wait for the release of Micronaut 4.0 release, it will include the latest version of this module. Or you can try the milestone version of Micronaut: https://micronaut.io/launch/.
