### ISSUE TITLE
Support for Micronaut serialization in addition to existing Jackson Databinding

### ISSUE THREAD

**Issue by ianibo** [micronaut-projects/micronaut-graphql#357]
### Feature description

**It would be ideal if micronaut-graphql worked out of the box with micronaut-serialization as well as the default jackson databinding.**

detail:

I'm working on a project which has targeted micronaut serialization over jackson. It seems that when using micronaut-serialization any attempt to access the graphql endpoint ends in an "Internal Server Error: Specific serializer required!" exception. The same project, switching back to jackson serialization works fine, so this feels like a feature request rather than a bug.

Example project that demonstrates the failure is here: https://github.com/ianibo/mn-graphql-without-jackson. Project is a straightforward implementation of the "Hello" sample with changes limited to build.gradle and Application.java (Where @SerdeImport is applied to GraphQLWsResponse.class, 
GraphQLResponseBody.class and GraphQLRequestBody.class).

Thanks :)

**Comment by timyates** [comment]
With Micronaut 4 and GraphQL 4.0.2, this works out of the box, and doesn't require SerdeImport any more.

I'll close this now, please raise a new issue if it doesn't work for you 👍
