### ISSUE TITLE
Add support for OneGraph GraphiQL Explorer

### ISSUE THREAD

**Issue by raderio** [micronaut-projects/micronaut-graphql#4]
https://www.onegraph.com/blog/2019/01/24/How_OneGraph_onboards_users_new_to_GraphQL.html#introducing-the-onegraph-graphiql-explorer

**Comment by marceloverdijk** [comment]
For now we only support GraphiQL.
In the future we might consider supporting other popular GraphQL clients like https://github.com/prisma/graphql-playground and/or https://altair.sirmuel.design/.

**Comment by imolorhe** [comment]
@Sparow199 has done some work adding Altair to https://github.com/graphql-java-kickstart/graphql-spring-boot. That might be a good starting point for this implementation (whenever you guys would want to implement it).
