### ISSUE TITLE
No bean introspection available for type [class io.micronaut.configuration.graphql.GraphQLRequestBody]

### ISSUE THREAD

**Issue by kluivert-queiroz** [micronaut-projects/micronaut-graphql#426]
Hi guys, I'm creating a Micronaut application and had an issue with GraphQL requests, although everything else is working fine. I followed the docs and created a minimal reproducible app. Am I missing anything or is it definitely a bug?
Thanks in advance!
### Expected Behavior

GraphQL library should run just fine.

### Actual Behaviour

Below error is thrown for every graphql request
```json
{
  "_links": {
    "self": [
      {
        "href": "/graphql",
        "templated": false
      }
    ]
  },
  "_embedded": {
    "errors": [
      {
        "message": "Internal Server Error: No bean introspection available for type [class io.micronaut.configuration.graphql.GraphQLRequestBody]. Ensure the class is annotated with io.micronaut.core.annotation.Introspected"
      }
    ]
  },
  "message": "Internal Server Error"
}
```

### Steps To Reproduce

Clone https://github.com/kluivert-queiroz/helloworld-graphql
Run ./gradlew run -t
Go to http://localhost:8080/graphiql

Or follow docs https://micronaut-projects.github.io/micronaut-graphql/latest/guide/#quickStart

### Environment Information

- JDK Version: 17
- Micronaut 4
- Using Kotlin

### Example Application

https://github.com/kluivert-queiroz/helloworld-graphql

### Version

4

**Comment by prashant-mns** [comment]
Hi, is there any progress on this, i am seeing the same issue as well. but i am using Java as the language.

**Comment by sdelamo** [comment]
a work around maybe to [add introspection info](https://docs.micronaut.io/latest/guide/#introspectedAnnotationOnAConfigurationClass) with: 

```java
import io.micronaut.core.annotation.Introspected;

@Introspected(classes = GraphQLRequestBody.class)
public class PersonConfiguration {
}
```
