### ISSUE TITLE
GraphQL Response has unexpected field "specification" in Micronaut 4.0.4

### ISSUE THREAD

**Issue by lonpalmer** [micronaut-projects/micronaut-graphql#440]
### Expected Behavior

A GraphQL response should only contain "data", "errors" and "extensions" fields.

### Actual Behaviour

Since version 4.0.4, the GraphQL Response object is getting a new field "specification" which duplicates the expected fields (data, errors and extensions).  This causes the server to send approx. twice the amount of data to the client and creates unexpected output as well. 

This appears to be a bug due to changes in Seredable w.r.t. GraphQL.

### Steps To Reproduce

A Micronaut server using GraphQL will return the unexpected field. 

### Environment Information

- Windows 11, Mac OS
- Micronaut 4.0.4

### Version

4.0.4

**Comment by dobe** [comment]
same here with mn 4.1.1, the problem occurs when using jackson databind when a class is annotated with @Serdable and has a @JsonAnyGetter annotation and using the injected ObjectMapper. this is all true for GraphQLResponseBody

this tests fails on a project generated with micronaut launch:

```kotlin

package com.example

import com.fasterxml.jackson.annotation.JsonAnyGetter
import com.fasterxml.jackson.annotation.JsonInclude
import com.fasterxml.jackson.databind.ObjectMapper
import io.micronaut.test.extensions.kotest5.annotation.MicronautTest
import io.kotest.core.spec.style.StringSpec
import io.kotest.matchers.shouldBe
import io.micronaut.serde.annotation.Serdeable

@MicronautTest(transactional = false, startApplication = false)
class TestanygetterTest(mapper: ObjectMapper) : StringSpec({

    "test getter" {
        val something = Something()
        val m = ObjectMapper()

        m.writeValueAsString(something) shouldBe """{"x":10}"""

        // this fails if Something is annotated with @Serdeable
        mapper.writeValueAsString(something) shouldBe """{"x":10}"""


    }
})

@Serdeable
class Something(
) {
    private val m = mutableMapOf<String, Any>("x" to 10)


    @JsonAnyGetter
    @JsonInclude
    fun getBlah(): Map<String, Any> = m
}
```

output

```
Expected :"{"x":10}"
Actual   :"{"blah":{"x":10},"x":10}"
```

**Comment by dobe** [comment]
since this breaks all graphql endpoints ... here is a workaround by overriding the serializer
Note: it seems that probably any classes annotated with Serdeable are somehow affected, so nested objects might still fail

```kotlin
@Primary
@Singleton
class LSJacksonGraphQLJsonSerializer(jsonMapper: JsonMapper) :
    JacksonGraphQLJsonSerializer(jsonMapper) {

    override fun serialize(obj: Any?): String {
        if (obj is GraphQLResponseBody) return super.serialize(obj.specification)
        return super.serialize(obj)
    }
}
```

**Comment by yawkat** [comment]
you can just set `jackson.bean-introspection-module: false` as a workaround

**Comment by guillermocalvo** [comment]
This issue should be fixed by: https://github.com/micronaut-projects/micronaut-core/pull/9872
