### ISSUE TITLE
GraphQL returns empty object if query returns empty collection or null

### ISSUE THREAD

**Issue by kenneks** [micronaut-projects/micronaut-graphql#489]
### Expected Behavior

Expecting `data` (and query name key) to be part of response when execution of the requested operation has been started.

Expected response:
```
{
    "data": {
        "bookById": null
    }
}
```

### Actual Behaviour

I tried upgrading from 4.0.5 to 4.2.3 and faced an issue where an empty object `{}` is returned if a query returns an empty collection or null.

Bug might have been introduced already in 4.1.0

Actual response:
```
{}
```

### Steps To Reproduce

1. [Download](https://guides.micronaut.io/latest/micronaut-graphql-gradle-kotlin.zip) and unzip the example application (https://guides.micronaut.io/latest/micronaut-graphql-gradle-kotlin.html)
2. Verify that the query in the guide over works as expected:
```
{
  bookById(id:"book-1") {
    name,
    pageCount,
    author {
      firstName
      lastName
    },
  }
}
```
3. Now try to query a book that doesn't exist, e.g. "book-xxx". Response is now `{}`

### Version

4.2.3

**Comment by timyates** [comment]
This seems to be an issue when using micronaut-databind-jackson.  Switching to use `io.micronaut.serde:micronaut-serde-jackson` seems to make it work correctly...

See also https://github.com/micronaut-projects/micronaut-graphql/issues/462

**Comment by sdelamo** [comment]
You can configuration Jackson not not to drop null or empty values by setting: 

`src/main/resources/application.properties`

```properties
jackson.serializationInclusion=ALWAYS
```
