### ISSUE TITLE
ServerRequestContext.currentRequest() is empty when enable-automatic-context-propagation: true

### ISSUE THREAD

**Issue by vad3x** [micronaut-projects/micronaut-graphql#495]
### Expected Behavior

`ServerRequestContext.currentRequest()` should not be empty.

### Actual Behaviour

ServerRequestContext.currentRequest() is empty when `enable-automatic-context-propagation: true` which breaks main services such as `SecurityService`.

### Steps To Reproduce

1. add `implementation("io.micronaut.reactor:micronaut-reactor")` to gradle.
2. add `implementation("io.micrometer:context-propagation")`.
3. Run the app.
4. `ServerRequestContext.currentRequest()` is empty for `DataFetcher`s.

Data fetcher example:
```java
@Singleton
public class GraphQLDataFetchers {
    private static final Logger LOG = LoggerFactory.getLogger(GraphQLDataFetchers.class);

    private final DbRepository dbRepository;

    public GraphQLDataFetchers(DbRepository dbRepository) {
        this.dbRepository = dbRepository;
    }

    public DataFetcher<Book> getBookByIdDataFetcher() {
        return dataFetchingEnvironment -> {
            // should not be empty, but empty
            LOG.info("currentRequest={}", ServerRequestContext.currentRequest());

            String bookId = dataFetchingEnvironment.getArgument("id");
            return dbRepository.findAllBooks()
                    .stream()
                    .filter(book -> book.getId().equals(bookId))
                    .findFirst()
                    .orElse(null);
        };
    }
}
```

Setting `enable-automatic-context-propagation: false` makes `ServerRequestContext.currentRequest()` to be not empty.

```yaml
reactor:
  enable-automatic-context-propagation: false
```

The workaround I found is to avoid using `io.micronaut.core.async.publisher.Publishers.*` library.
For example, If I override [DefaultGraphQLInvocation.invoke](https://github.com/micronaut-projects/micronaut-graphql/blob/master/graphql/src/main/java/io/micronaut/configuration/graphql/DefaultGraphQLInvocation.java#L84) with:

```java
    @Override
    public Publisher<ExecutionResult> invoke(
            GraphQLInvocationData invocationData,
            HttpRequest httpRequest,
            @Nullable MutableHttpResponse<String> httpResponse) {
        ExecutionInput.Builder executionInputBuilder = ExecutionInput.newExecutionInput()
                .query(invocationData.getQuery())
                .operationName(invocationData.getOperationName())
                .variables(invocationData.getVariables());
        if (dataLoaderRegistry != null) {
            executionInputBuilder.dataLoaderRegistry(dataLoaderRegistry.get());
        }
        ExecutionInput executionInput = executionInputBuilder.build();

        return Flux.from(graphQLExecutionInputCustomizer.customize(executionInput, httpRequest, httpResponse))
                // replaced Publishers.fromCompletableFuture with Mono.fromFuture
                .flatMap(customizedExecutionInput -> Mono.fromFuture(() -> {
                    try {
                        return graphQL.executeAsync(customizedExecutionInput);
                    } catch (Throwable e) {
                        CompletableFuture future = new CompletableFuture();
                        future.completeExceptionally(e);
                        return future;
                    }
                }));
    }
```

And [DefaultGraphQLExecutionInputCustomizer.customize](https://github.com/micronaut-projects/micronaut-graphql/blob/master/graphql/src/main/java/io/micronaut/configuration/graphql/DefaultGraphQLExecutionInputCustomizer.java#L45)
```java
    @Override
    public Publisher<ExecutionInput> customize(ExecutionInput executionInput, HttpRequest httpRequest,
            @Nullable MutableHttpResponse<String> httpResponse) {
        // replaced Publishers.just with Flux.just
        return Flux.just(executionInput);
    }
```

it now starts working well (`ServerRequestContext.currentRequest()` is NOT empty for `DataFetcher`s).

### Environment Information

- Java v17.0.9
- Gradle v8.4
- Micronaut 4.2.3

### Version

5.2.3

**Comment by jeremyg484** [comment]
@vad3x Thanks for reporting. Just want to clarify, did you also have

```
implementation("io.micrometer:context-propagation")
```

specified in your original non-working version?

**Comment by vad3x** [comment]
Hi @jeremyg484, yes, I have `implementation("io.micrometer:context-propagation")` in both versions.
