### ISSUE TITLE
Graphql BOM depends on old snapshot of  graphql-java-extended-scalars  

### ISSUE THREAD

**Issue by johndevs** [micronaut-projects/micronaut-graphql#575]
### Expected Behavior

My expectation is that the [micronaut-graphql-bom](https://mvnrepository.com/artifact/io.micronaut.graphql/micronaut-graphql-bom) would depend on `graphql-java-extended-scalars:22.0` 

### Actual Behaviour

Currently it depends on [2023-01-24T02-11-56-babda5f](https://mvnrepository.com/artifact/com.graphql-java/graphql-java-extended-scalars/2023-01-24T02-11-56-babda5f) which is a master branch snapshot.

### Steps To Reproduce

See https://mvnrepository.com/artifact/io.micronaut.graphql/micronaut-graphql-bom/4.5.0

### Version

4.5.0

**Comment by altro3** [comment]
@johndevs I fixed it here: https://github.com/micronaut-projects/micronaut-graphql/pull/572

FYI: This repo just aggregating all micronaut projects BOMs. If you have a problem or suggestion about one of them - need to create issue in project repo. In you case this is https://github.com/micronaut-projects/micronaut-graphql
