### ISSUE TITLE
@Blocking annonation doesn't work in datafetcher 

### ISSUE THREAD

**Issue by gauravphoenix** [micronaut-projects/micronaut-graphql#81]
I am experimenting with a "hello world" graphql example and I observe that if I put a `@Blocking` annotation on the datafetcher method, I still see that the Micronaut is executing the method within the netty's eventloop. 
```java
@Blocking
@Override
	public String get(DataFetchingEnvironment env) implements DataFetcher<String> {
              return "foo"
}
```

and this is how I am doing runtime wiring 

```
RuntimeWiring runtimeWiring = RuntimeWiring.newRuntimeWiring()																							 .type("Query", typeWiring -> typeWiring																									 .dataFetcher("fooQuery", myDataFetcher))																							 .build();
```

I would expect to see that the method is being executed in some worker thread pool and not the netty's event loop. 

I also tried `@ExecuteOn` approach but that didn't work either :(

**Comment by ilopmar** [comment]
@gauravphoenix can you please share a sample app that reproduces the issue?

**Comment by gauravphoenix** [comment]
nevermind, I abandoned the project so I won't be able to spend time to reproduce.

**Comment by davidhesson** [comment]
I am pretty sure this was never fixed. All because a sample app wasn't provided?
